baseurl: https://www.lieverdeleven.nl
title: Liever de leven
theme: ananke
uglyURLs: true

defaultContentLanguage: nl

taxonomies:
  type: types

SectionPagesMenu: main

# menu:
#   main:
#     - url: /
#       name: Home
#       weight: 1
#     - url: /blog.html
#       name: Blog
#       weight: 2
#     - url: /fictie.html
#       name: Fictie
#       weight: 2
