baseurl: https://www.lieverdeleven.nl
title: Liever de leven
theme: ananke
uglyURLs: true

defaultContentLanguage: nl

taxonomies:
  type: types

SectionPagesMenu: main

params:
  featured_image: /images/bg.jpg
  disable_share: true
